theme: minima
title: datascience portfolio
author: Dihella Ikapitte
description: 
An example of a data science portfolio showcasing coursework and projects. Designed to highlight coding skills, data analysts, and project-based learning.
